### ISSUE TITLE
Custom start/end times don't work on Windows

### ISSUE THREAD

**Issue by vtnate** [urbanopt/urbanopt-ditto-reader#26]
Full year runs regardless of start-time and end-time flags provided to urbanopt cli.

The quotes around date and time making them a single string don't get read correctly by Windows machines.

A possible workaround is to separate the date and time blocks so they can be called separately. Having a default for time would be nice, so only the date needs to be provided. Ugh, Windows.

**Comment by tarekelgindy** [comment]
Is this still an issue? Any changes you'd like made for this?

**Comment by vtnate** [comment]
The problem as stated still exists. However, we successfully built the suggested workaround in the urbanopt cli, so nothing needs to be changed here. Closing this ticket.
