### ISSUE TITLE
Transformer loading factors incorrect in >=v0.3.9

### ISSUE THREAD

**Issue by vtnate** [urbanopt/urbanopt-ditto-reader#27]
https://3.basecamp.com/4298486/buckets/13938778/messages/4048653852

`transformer loading factors in the double digits` and `it appears that the reader might just be leaving several transformers connected backwards.`

**URGENT:** Ladybug is using v0.3.8 until this bug is fixed

**Comment by tarekelgindy** [comment]
Should be addressed in the latest PR
