### ISSUE TITLE
Transformer automatic size upgrading doesn't work

### ISSUE THREAD

**Issue by vtnate** [urbanopt/urbanopt-ditto-reader#30]
The loads from the example project are much larger than anything the auto-sizing routine can handle, so no changes are made to the transformers.

**Comment by tarekelgindy** [comment]
So this is probably due to changes that were made to urbanopt after the example was created.
The example folder has been updated to be compatible with the current version of urbanopt.

**Comment by vtnate** [comment]
Tarek's [update of the example](https://github.com/urbanopt/urbanopt-ditto-reader/commit/cb4917bb144bedbf7587c587472f9994b9b5ed67) folder helped a lot, but some loads in the geojson file are too large for the existing transformers and power lines. Options to resolve (in order of increasing correctness and effort):
1. Do nothing - 2 example transformers are overloaded by 25% which is probably physically possible
1. Use smaller loads
2. Update electrical equipment in the example to handle the larger loads
3. Update RNM to be able to handle large loads such as in our example

Which would you prefer @kflemin ?

**Comment by tarekelgindy** [comment]
This should be addressed with the latest pull request. Very large loads now connect directly to medium voltage. In the powerflow results there are limited low voltages (e.g. on Feature 7) and very few line overloads - all of which are not too large.
@vtnate  if this is working correctly for you we can close out this issue.
