### ISSUE TITLE
Start and end time not being processes by URBANopt CLI opendss command

### ISSUE THREAD

**Issue by tanushree04** [urbanopt/urbanopt-ditto-reader#32]
On adding the start and end time to the opendss command, an error is being thrown in windows for an extra time argument.

**Comment by tarekelgindy** [comment]
Do you have example output for this?
If I was to guess I'd say it's because the path to the opendss_folder parameter in the config is pointing to the incorrect location

**Comment by vtnate** [comment]
This is a duplicate of #26 which has been resolved in the urbanopt cli. Closing this ticket.
